import { Injectable, Inject } from '@nestjs/common';
import { LOGGER_SERVICE, PinoLoggerService } from '@goalxi/logger';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import {
  MatchEntity,
  MatchStatus,
  MatchType,
  LeagueEntity,
  TeamEntity,
  computeFirstMatchAt,
} from '@goalxi/database';

/**
 * Senior round-robin options. The historical youth-league
 * branch was retired when the youth pipeline was paused —
 * the dedicated `youth_league` / `youth_team` rows are no
 * longer generated by init, and youth fixtures no longer
 * ride the senior schedule. See `computeFirstMatchAt` for
 * the new "next-Monday 00:00 UTC" anchor rule.
 */
interface RoundRobinOptions {
  /** Senior `league_id` the fixtures belong to. */
  leagueId: string;
  /** First kickoff instant (UTC). All rounds step off this. */
  anchorAt: Date;
  /** Season number stamped onto every match. */
  season: number;
}

@Injectable()
export class ScheduleGenerator {
  constructor(
    @Inject(LOGGER_SERVICE)
    private readonly logger: PinoLoggerService,
    @InjectRepository(MatchEntity)
    private readonly matchRepo: Repository<MatchEntity>,
    @InjectRepository(LeagueEntity)
    private readonly leagueRepo: Repository<LeagueEntity>,
    @InjectRepository(TeamEntity)
    private readonly teamRepo: Repository<TeamEntity>,
  ) {}

  /**
   * Generate the full Season 1 schedule for every senior
   * league. Idempotent — if any season-1 match row already
   * exists, the call no-ops and the existing schedule is
   * left in place.
   *
   * `initDate` is the calendar day the user ran
   * `pnpm init:run --init-date=...` on. The first kickoff
   * instant is computed from this via `computeFirstMatchAt`
   * (next-Monday 00:00 UTC) so the season always opens on a
   * weekday boundary regardless of what day init ran on.
   *
   * 30 rounds per league (16 teams × double round-robin) ×
   * 85 leagues = 20,400 matches for the full pyramid.
   */
  async generateSeason1Schedule(initDate: Date): Promise<void> {
    const count = await this.matchRepo.count({ where: { season: 1 } });
    if (count > 0) {
      this.logger.info(
        `[ScheduleGenerator] ${count} season-1 match(es) already exist, skipping`,
      );
      return;
    }

    const firstKickoff = computeFirstMatchAt(initDate);
    this.logger.info(
      `[ScheduleGenerator] Generating Season 1 schedule (anchor=${firstKickoff.toISOString()})...`,
    );

    const total = await this.generateSeniorFixtures({
      anchorAt: firstKickoff,
      season: 1,
    });

    this.logger.info(
      `[ScheduleGenerator] Generated ${total} senior match(es) for Season 1`,
    );
  }

  // ---------- senior fixtures ----------

  private async generateSeniorFixtures(options: {
    anchorAt: Date;
    season: number;
  }): Promise<number> {
    const leagues = await this.leagueRepo.find();
    let total = 0;
    for (const league of leagues) {
      const teams = await this.teamRepo.find({
        where: { leagueId: league.id },
      });
      const teamIds = teams.map((t) => t.id);

      if (teamIds.length < 4) {
        this.logger.warn(
          `[ScheduleGenerator] League "${league.name}" has only ${teamIds.length} teams, skipping`,
        );
        continue;
      }

      const matches = this.generateRoundRobin(teamIds, {
        leagueId: league.id,
        anchorAt: options.anchorAt,
        season: options.season,
      });
      await this.matchRepo.save(matches);
      total += matches.length;
    }
    return total;
  }

  // ---------- shared round-robin ----------

  /**
   * Standard circle method. Round 0 puts `teamIds[0]` at
   * home against the rotated slot; the rest of the round
   * pairs the outer + inner positions. Spacing is one full
   * week per round, so the season stretches cleanly across
   * 30 weeks for a 16-team league. The first kickoff is
   * the `anchorAt` instant; subsequent rounds step off in
   * 7-day increments.
   */
  private generateRoundRobin(
    teamIds: string[],
    options: RoundRobinOptions,
  ): Partial<MatchEntity>[] {
    const matches: Partial<MatchEntity>[] = [];
    const numRounds = teamIds.length - 1;
    const fixedTeam = teamIds[0];
    const rotatingTeams = teamIds.slice(1);

    // First leg — every team hosts once in the first N-1 rounds.
    for (let round = 0; round < numRounds; round++) {
      const matchups = this.generateRoundMatchups(
        fixedTeam,
        this.rotateTeams(rotatingTeams, round),
      );

      for (const { home, away } of matchups) {
        matches.push({
          leagueId: options.leagueId,
          youthLeagueId: null,
          season: options.season,
          week: round + 1,
          round: round + 1,
          homeTeamId: home,
          awayTeamId: away,
          status: MatchStatus.SCHEDULED,
          type: MatchType.LEAGUE,
          tacticsLocked: false,
          homeForfeit: false,
          awayForfeit: false,
          scheduledAt: this.matchStart(round, options.anchorAt),
        });
      }
    }

    // Second leg — same pairings, venues reversed.
    for (let round = 0; round < numRounds; round++) {
      const matchups = this.generateRoundMatchups(
        fixedTeam,
        this.rotateTeams(rotatingTeams, round),
      );

      for (const { home, away } of matchups) {
        matches.push({
          leagueId: options.leagueId,
          youthLeagueId: null,
          season: options.season,
          week: numRounds + round + 1,
          round: numRounds + round + 1,
          homeTeamId: away,
          awayTeamId: home,
          status: MatchStatus.SCHEDULED,
          type: MatchType.LEAGUE,
          tacticsLocked: false,
          homeForfeit: false,
          awayForfeit: false,
          scheduledAt: this.matchStart(
            numRounds + round,
            options.anchorAt,
          ),
        });
      }
    }

    return matches;
  }

  /**
   * Round 0 lands on `anchorAt` (already at the top of a
   * Monday hour by `computeFirstMatchAt`). Each subsequent
   * round steps by 7 days. No intra-week half-rounds — the
   * design is "one round per week".
   */
  private matchStart(round: number, anchorAt: Date): Date {
    return new Date(anchorAt.getTime() + round * 7 * 24 * 60 * 60 * 1000);
  }

  private generateRoundMatchups(
    fixedTeam: string,
    rotatingTeams: string[],
  ): Array<{ home: string; away: string }> {
    const matchups: Array<{ home: string; away: string }> = [];
    matchups.push({ home: fixedTeam, away: rotatingTeams[0] });

    for (let i = 1; i < rotatingTeams.length / 2; i++) {
      matchups.push({
        home: rotatingTeams[rotatingTeams.length - i],
        away: rotatingTeams[i],
      });
    }

    return matchups;
  }

  private rotateTeams(teams: string[], round: number): string[] {
    // Rotate by `round` positions so each round of the
    // round-robin gets a fresh pairing set. The previous
    // implementation only rotated by 1 every call, which
    // collapsed the schedule: every round reused the same
    // 8 matchups, so the "round-robin" was really just a
    // fixed team pinned against the rotating slot.
    const rotated = [...teams];
    for (let i = 0; i < round; i++) {
      const last = rotated.pop()!;
      rotated.unshift(last);
    }
    return rotated;
  }
}
