export enum TransactionType {
  // 收入
  TICKET_INCOME = 'TICKET_INCOME',
  SPONSORSHIP = 'SPONSORSHIP',
  TRANSFER_IN = 'TRANSFER_IN',
  PRIZE_MONEY = 'PRIZE_MONEY',
  // 支出
  WAGES = 'WAGES',
  STAFF_WAGES = 'STAFF_WAGES',
  TRANSFER_OUT = 'TRANSFER_OUT',
  FACILITY_UPGRADE = 'FACILITY_UPGRADE',
  STADIUM_MAINTENANCE = 'STADIUM_MAINTENANCE',
  MEDICAL = 'MEDICAL',
  YOUTH_TEAM = 'YOUTH_TEAM',
}

export const FINANCE_CONSTANTS = {
  // 赞助商基础值（周）
  SPONSORSHIP_BASE: { 1: 100000, 2: 70000, 3: 50000, 4: 40000, 5: 30000 },
  // 员工工资（周）
  STAFF_WAGE: { 1: 2000, 2: 4000, 3: 8000, 4: 15000, 5: 25000 },
  // 球场维护费（周/每座位）
  STADIUM_MAINTENANCE_PER_SEAT: 2,
  // 青训运营（周）
  YOUTH_TEAM_COST: 20000,
  // 伤病医疗（天）
  MEDICAL_COST_PER_DAY: 1000,
} as const;
