import { Test, TestingModule } from '@nestjs/testing';
import { getRepositoryToken } from '@nestjs/typeorm';
import {
  LeagueEntity,
  LeagueStandingEntity,
  MatchEntity,
  MatchStatus,
  MatchType,
  GAME_SETTINGS,
} from '@goalxi/database';
import { SeasonSchedulerService } from './season-scheduler.service';
import { LOGGER_SERVICE_PROVIDER } from '../test-utils/test-logger';

/**
 * Season 2+ fixture generation.
 *
 * These are the only paths through `SeasonSchedulerService` — season 1
 * is generated by `bootstrap/generators/schedule.generator.ts`, which
 * derives kickoff times with `matchStart(round, weekOneMonday)`. That
 * divergence is why the bug this file pins was invisible in season 1
 * and produced a broken fixture list from season 2 onward.
 */
describe('SeasonSchedulerService', () => {
  let service: SeasonSchedulerService;
  let matchRepository: {
    save: jest.Mock;
    count: jest.Mock;
  };
  let leagueRepository: { find: jest.Mock };
  let standingRepository: { find: jest.Mock };

  const TEAM_IDS = Array.from({ length: 16 }, (_, i) => `team-${i + 1}`);
  // A Wednesday, so `calculateFirstLegDates` doesn't have to walk.
  const START = new Date('2026-04-08T00:00:00.000Z'); // Wed

  beforeEach(async () => {
    matchRepository = {
      save: jest.fn().mockImplementation((m) => m),
      count: jest.fn().mockResolvedValue(0),
    };
    leagueRepository = { find: jest.fn().mockResolvedValue([]) };
    standingRepository = { find: jest.fn().mockResolvedValue([]) };
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        SeasonSchedulerService,
        LOGGER_SERVICE_PROVIDER,
        { provide: getRepositoryToken(MatchEntity), useValue: matchRepository },
        {
          provide: getRepositoryToken(LeagueEntity),
          useValue: leagueRepository,
        },
        {
          provide: getRepositoryToken(LeagueStandingEntity),
          useValue: standingRepository,
        },
      ],
    }).compile();
    service = module.get(SeasonSchedulerService);
  });

  const gen = () =>
    (service as any).generateDoubleRoundRobin(
      TEAM_IDS,
      'league-1',
      2,
      START,
    ) as Partial<MatchEntity>[];

  it('gives every match a defined kickoff time', () => {
    // The old code fell back to `firstLegDates[round * 2]` when
    // `firstLegDates[round * 2 + i]` was undefined, which silently
    // collapsed 6 of the last round's 8 matches onto one timestamp
    // (and most of the second leg likewise).
    const matches = gen();
    expect(matches.length).toBe(16 * 15); // double round-robin
    for (const m of matches) {
      expect(m.scheduledAt).toBeInstanceOf(Date);
      expect(Number.isNaN((m.scheduledAt as Date).getTime())).toBe(false);
    }
  });

  it('REGRESSION: all matches sharing a kickoff time form one full matchday', () => {
    // `dates[round * 2 + i]` with `i` = match-within-round spread a
    // single matchday across four calendar weeks (Wed r0, Sat r0,
    // Wed r1, Sat r1, ...).
    //
    // NOTE: the `round` column is `(r % 2) + 1` — it encodes which day
    // of the match-week (1 = Wed, 2 = Sat), NOT the calendar round, so
    // it cannot be used to group. Group by timestamp instead.
    const byTimestamp = new Map<number, Partial<MatchEntity>[]>();
    for (const m of gen()) {
      const key = (m.scheduledAt as Date).getTime();
      byTimestamp.set(key, [...(byTimestamp.get(key) ?? []), m]);
    }
    // 16 teams / 2 = 8 matches per matchday; 15 rounds x 2 legs = 30 slots.
    expect(byTimestamp.size).toBe(30);
    for (const [ts, group] of byTimestamp) {
      expect({ ts, matches: group.length }).toEqual({ ts, matches: 8 });
    }
  });

  it('REGRESSION: no timestamp collision across the season', () => {
    // Before the fix, six matches in round 14 (and most of leg 2)
    // shared the single fallback timestamp — i.e. some timestamps
    // carried far more than one matchday's worth of matches.
    const matches = gen();
    const counts = new Map<number, number>();
    for (const m of matches) {
      const key = (m.scheduledAt as Date).getTime();
      counts.set(key, (counts.get(key) ?? 0) + 1);
    }
    // 30 distinct kickoff slots (15 first-leg + 15 second-leg).
    expect(counts.size).toBe(30);
    // The biggest legitimate collision is one matchday: 8 matches.
    expect(Math.max(...counts.values())).toBe(8);
  });

  it('REGRESSION: kickoff alternates Wed / Sat across rounds', () => {
    // Matches `ScheduleGenerator.matchStart`: even rounds on the
    // Wednesday, odd rounds on the Saturday, two rounds per week
    // (so 15 rounds span 8 calendar weeks).
    const allTimes = [
      ...new Set(gen().map((m) => (m.scheduledAt as Date).getTime())),
    ].sort((a, b) => a - b);
    // First leg is the earliest 15 slots; the second leg is the same
    // pattern shifted 15 weeks.
    const leg1 = allTimes.slice(0, 15);
    const days = leg1.map((t) => new Date(t).getUTCDay());
    expect(days).toEqual([
      3, 6, 3, 6, 3, 6, 3, 6, 3, 6, 3, 6, 3, 6, 3, // Wed, Sat, ... (r=14 is even)
    ]);
    // Wed->Sat = 3 days, Sat->Wed = 4 days.
    const gaps = leg1
      .map((t, i) => (i === 0 ? null : (t - leg1[i - 1]) / 86400000))
      .slice(1);
    for (const g of gaps) {
      expect([3, 4]).toContain(g);
    }
    // The second leg mirrors the first exactly, 15 weeks later.
    const leg2 = allTimes.slice(15);
    expect(leg2).toHaveLength(15);
    for (let i = 0; i < 15; i++) {
      expect((leg2[i] - leg1[i]) / 86400000).toBe(15 * 7);
    }
  });

  it('REGRESSION: kickoff hour is MATCH_KICKOFF_HOUR_UTC', () => {
    for (const m of gen()) {
      expect((m.scheduledAt as Date).getUTCHours()).toBe(
        GAME_SETTINGS.MATCH_KICKOFF_HOUR_UTC,
      );
      expect((m.scheduledAt as Date).getUTCMinutes()).toBe(0);
    }
  });

  it('the second leg of each pairing is at least 7 days after the first', () => {
    const byPairing = new Map<string, number[]>();
    for (const m of gen()) {
      const key = [m.homeTeamId, m.awayTeamId].sort().join('|');
      const list = byPairing.get(key) ?? [];
      list.push((m.scheduledAt as Date).getTime());
      byPairing.set(key, list);
    }
    expect(byPairing.size).toBe((16 * 15) / 2);
    for (const [key, times] of byPairing) {
      expect(times).toHaveLength(2);
      const [a, b] = times.sort((x, y) => x - y);
      expect({ key, gapDays: (b - a) / (24 * 60 * 60 * 1000) }).toEqual({
        key,
        gapDays: expect.any(Number),
      });
      expect(b - a).toBeGreaterThanOrEqual(7 * 24 * 60 * 60 * 1000);
    }
  });

  it('every pairing plays once at each venue (double round-robin contract)', () => {
    const venues = new Map<string, Set<string>>();
    for (const m of gen()) {
      const key = [m.homeTeamId, m.awayTeamId].sort().join('|');
      const set = venues.get(key) ?? new Set<string>();
      set.add(`${m.homeTeamId}>${m.awayTeamId}`);
      venues.set(key, set);
    }
    for (const set of venues.values()) {
      expect(set.size).toBe(2);
    }
  });

  it('weeks stay within the season length so the transition crons can fire', () => {
    // `SeasonTransitionService` keys on `week`, and the playoff gate
    // checks week 15 / 16. A schedule whose `week` runs past
    // SEASON_LENGTH_WEEKS would silently never satisfy those gates.
    const weeks = gen().map((m) => m.week as number);
    expect(Math.min(...weeks)).toBeGreaterThanOrEqual(1);
    expect(Math.max(...weeks)).toBeLessThanOrEqual(
      GAME_SETTINGS.SEASON_LENGTH_WEEKS,
    );
  });

  it('stamps SCHEDULED / LEAGUE so the completion cron picks them up', () => {
    for (const m of gen()) {
      expect(m.status).toBe(MatchStatus.SCHEDULED);
      expect(m.type).toBe(MatchType.LEAGUE);
    }
  });

  describe('generateNextSeasonSchedule idempotency', () => {
    it('REGRESSION: skips a league that already has a schedule for the season', async () => {
      // There was no guard at all, so a second
      // `checkAndProcessSeasonStart` run inserted a complete duplicate
      // fixture list (~20,400 rows) — teams playing every opponent
      // twice in the same week slots, with no unique constraint on
      // `match` to stop it. Reachable because that method
      // logs-and-rethrows: step 4 failing after steps 1-3 committed
      // means next week's cron re-runs it.
      leagueRepository.find.mockResolvedValue([
        { id: 'league-1', maxTeams: 16 } as any,
      ]);
      // Season 2 already has fixtures for this league.
      matchRepository.count.mockResolvedValue(240);

      const result = await service.generateNextSeasonSchedule(1);

      expect(result).toEqual([]);
      expect(matchRepository.save).not.toHaveBeenCalled();
      expect(standingRepository.find).not.toHaveBeenCalled();
      // The guard is keyed on (leagueId, season).
      expect(matchRepository.count).toHaveBeenCalledWith({
        where: { leagueId: 'league-1', season: 2 },
      });
    });

    it('emits a schedule when the league has none yet', async () => {
      leagueRepository.find.mockResolvedValue([
        { id: 'league-1', maxTeams: 16 } as any,
      ]);
      matchRepository.count.mockResolvedValue(0);
      standingRepository.find.mockResolvedValue(
        TEAM_IDS.map((id) => ({ teamId: id })),
      );

      const result = await service.generateNextSeasonSchedule(1);

      expect(matchRepository.save).toHaveBeenCalledTimes(1);
      expect(result).toHaveLength(16 * 15);
    });

    it('a second run over the same season is a no-op', async () => {
      leagueRepository.find.mockResolvedValue([
        { id: 'league-1', maxTeams: 16 } as any,
      ]);
      standingRepository.find.mockResolvedValue(
        TEAM_IDS.map((id) => ({ teamId: id })),
      );
      matchRepository.count.mockResolvedValue(0);

      await service.generateNextSeasonSchedule(1);
      const firstCount = matchRepository.save.mock.calls.length;
      expect(firstCount).toBe(1);

      // Simulate the first run having written the rows.
      matchRepository.count.mockResolvedValue(240);
      const second = await service.generateNextSeasonSchedule(1);

      expect(second).toEqual([]);
      expect(matchRepository.save).toHaveBeenCalledTimes(firstCount);
    });
  });
});