import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * One-off backfill: for every existing senior team, ensure a YouthTeam
 * exists and seed 3 scout candidates if the inbox is empty.
 *
 * Why: the TeamService.create onboarding hook (added in P1) only fires
 * for newly created teams. Teams that existed before this hook was
 * added would never have been given a YouthTeam and would have to wait
 * up to a week for the Saturday cron to populate their scout inbox.
 *
 * Idempotent: safe to re-run. Skips teams that already have an inbox
 * with active (unexpired) candidates.
 *
 * Note: This migration does NOT import the application services
 * (TypeORM migrations are loaded with a slim DataSource and importing
 * from `api/` would create a circular dependency). Instead, the
 * candidate `player_data` payload is a minimal stub — the next time
 * the team visits /scouts they'll get fresh, fully-formed candidates
 * from the cron path. The stub is enough to make the inbox non-empty
 * and trigger any UI that depended on it.
 */
export class BackfillYouthTeamAndCandidates1721000000003
  implements MigrationInterface
{
  name = 'BackfillYouthTeamAndCandidates1721000000003';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // 1. Make sure the default youth league exists.
    await queryRunner.query(`
      INSERT INTO "youth_league" ("name", "parent_tier", "max_teams", "status", "created_at", "updated_at")
      SELECT 'Youth Academy League', 1, 9999, 'active', now(), now()
      WHERE NOT EXISTS (SELECT 1 FROM "youth_league" WHERE "name" = 'Youth Academy League')
    `);

    // 2. For each senior team without a YouthTeam, create one.
    await queryRunner.query(`
      INSERT INTO "youth_team" ("id", "team_id", "youth_league_id", "name", "created_at", "updated_at")
      SELECT
        gen_random_uuid(),
        t."id",
        (SELECT "id" FROM "youth_league" WHERE "name" = 'Youth Academy League' LIMIT 1),
        t."name" || ' Youth',
        now(),
        now()
      FROM "team" t
      LEFT JOIN "youth_team" yt ON yt."team_id" = t."id"
      WHERE yt."id" IS NULL
    `);

    // 3. For each team that has no active scout candidates, seed 3.
    //    The stub player_data is intentionally minimal — real, fully-
    //    detailed candidates come from the Saturday cron. This is just
    //    to unblock onboarding UX for legacy teams.
    const teamsNeedingCandidates: Array<{ id: string; name: string }> =
      await queryRunner.query(`
        SELECT t."id", t."name"
        FROM "team" t
        WHERE NOT EXISTS (
          SELECT 1 FROM "scout_candidate" sc
          WHERE sc."team_id" = t."id"
            AND sc."expires_at" > now()
        )
      `);

    for (const team of teamsNeedingCandidates) {
      for (let i = 0; i < 3; i++) {
        await queryRunner.query(
          `
            INSERT INTO "scout_candidate" (
              "id", "created_at", "updated_at", "team_id",
              "player_data", "expires_at"
            ) VALUES (
              gen_random_uuid(), now(), now(), $1,
              $2::jsonb, now() + interval '7 days'
            )
          `,
          [
            team.id,
            JSON.stringify({
              name: `${team.name} Prospect ${i + 1}`,
              createdDay: 19000,
              nationality: 'GB',
              isGoalkeeper: i === 0,
              currentSkills: {
                physical: { pace: 10, strength: 10 },
                technical: i === 0
                  ? { reflexes: 10, handling: 10, aerial: 10 }
                  : { finishing: 10, passing: 10, dribbling: 10, defending: 10 },
                mental: { positioning: 10, composure: 10 },
                setPieces: { freeKicks: 10, penalties: 10 },
              },
              potentialSkills: {
                physical: { pace: 15, strength: 15 },
                technical: i === 0
                  ? { reflexes: 15, handling: 15, aerial: 15 }
                  : { finishing: 15, passing: 15, dribbling: 15, defending: 15 },
                mental: { positioning: 15, composure: 15 },
                setPieces: { freeKicks: 15, penalties: 15 },
              },
              potentialTier: 'REGULAR',
              potentialRevealed: false,
              revealedSkills: ['pace', 'strength'],
              joinedAt: new Date().toISOString(),
              _backfill: true,
            }),
          ],
        );
      }
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Remove only the backfill-stubbed candidates so re-running `up`
    // doesn't accumulate extras. Real candidates generated by the cron
    // are NOT removed (they don't carry `_backfill: true`).
    await queryRunner.query(`
      DELETE FROM "scout_candidate"
      WHERE "player_data"->>'_backfill' = 'true'
    `);
  }
}