import { MigrationInterface, QueryRunner, TableUnique } from "typeorm";

export class AllowMultipleTeamsPerUser1733241000000 implements MigrationInterface {
    name = 'AllowMultipleTeamsPerUser1733241000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // Drop the unique constraint on user_id in team table
        // Since we don't know the exact name generated by TypeORM, we can try to drop it by column names
        // or we can query the information schema.
        // However, TypeORM usually names it UQ_ + hash.

        // Let's try to find the constraint name first
        const table = await queryRunner.getTable("team");
        const uniqueConstraint = table?.uniques.find(uq => uq.columnNames.indexOf("user_id") !== -1);

        if (uniqueConstraint) {
            await queryRunner.dropUniqueConstraint("team", uniqueConstraint);
        } else {
            // Fallback: try to drop by guessing the name or just altering the column
            // But altering column to drop unique is database specific.
            // In Postgres: ALTER TABLE "team" DROP CONSTRAINT "constraint_name"

            // If we can't find it via metadata, we might need to check if it exists in DB
            // For now, let's assume the metadata is correct or we can just run a raw query if we knew the name.

            // Let's try to remove the unique constraint by modifying the column
            // This might not work if there is a named constraint.

            // Alternative: Check if there is a constraint named 'UQ_team_user_id' or similar?
            // Usually TypeORM uses UQ_ + generated hash if not specified.

            // Let's just try to drop the constraint if we can find it. 
            // If not, we'll log a warning.
            console.warn("Could not find unique constraint on team.user_id to drop.");
        }
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Re-add the unique constraint
        await queryRunner.createUniqueConstraint("team", new TableUnique({
            columnNames: ["user_id"]
        }));
    }
}
