// Notification types matching the backend NotificationType enum

export enum NotificationType {
  // Match notifications
  MATCH_RESULT_WIN = 'MATCH_RESULT_WIN',
  MATCH_RESULT_LOSS = 'MATCH_RESULT_LOSS',
  MATCH_RESULT_DRAW = 'MATCH_RESULT_DRAW',

  // Player notifications
  PLAYER_SKILL_IMPROVED = 'PLAYER_SKILL_IMPROVED',
  PLAYER_SKILL_DECREASED = 'PLAYER_SKILL_DECREASED',
  PLAYER_INJURED = 'PLAYER_INJURED',
  PLAYER_RECOVERED = 'PLAYER_RECOVERED',

  // Transfer notifications
  PLAYER_PURCHASED = 'PLAYER_PURCHASED',
  PLAYER_SOLD = 'PLAYER_SOLD',
  AUCTION_OUTBID = 'AUCTION_OUTBID',
  AUCTION_WON = 'AUCTION_WON',
  AUCTION_LOST = 'AUCTION_LOST',

  // League notifications
  LEAGUE_POSITION_CHANGED = 'LEAGUE_POSITION_CHANGED',
  SEASON_STARTED = 'SEASON_STARTED',
  SEASON_ENDED = 'SEASON_ENDED',

  // System notifications
  TEAM_INVITATION = 'TEAM_INVITATION',
  SYSTEM_MESSAGE = 'SYSTEM_MESSAGE',
}
